#!/bin/bash

REQUEST_METHOD=POST \
CONTENT_TYPE="multipart/form-data; boundary=------WebKitFormBoundary" \
QUERY_STRING="id=123" \

echo -e "------WebKitFormBoundary\r\nContent-Disposition: form-data; name=\"file\"; filename=\"test.txt\"\r\nContent-Type: text/plain\r\n\r\nHello, World!\r\n------WebKitFormBoundary--\r\n" | ./upload.py

